### ISSUE TITLE
Is the license MIT?

### ISSUE THREAD

**Issue by tmylk** [Smerity/gzipstream#7]
@Smerity Hey,

I would like to incorporate gzipstream into smart_open as it is great for reading gz from S3 as in https://github.com/piskvorky/smart_open/pull/75

Is it ok to use it under MIT license as stated on the README page?

**Comment by Smerity** [comment]
Hey @tmylk,

The license is indeed MIT. I'm not quite sure how the GPL ended up in the LICENSE file. I've removed the LICENSE file and the README states it is MIT.

As noted in your referenced issue, the codebase hasn't been updated in a long time, but if it's still useful, feel free to use as best appropriate :)

P.S. Smart Open looks awesome - I'll remember to use it in relevant future projects =]
